Tensors-Data structures to store data 
rank=no.of dimensions 
shape=(no. of elements in each direction)
multiplication of which gives size

In [4]:
import numpy as np

In [14]:
arr=np.array(4)  #scalar/0d tensor

In [16]:
arr

array(4)

In [18]:
arr=np.array([1,2,3,4]) #1d tensor(vector)

In [20]:
arr

array([1, 2, 3, 4])

In [24]:
arr=np.array([[1,2,3,4],[5,6,7,8]]) #2d tensor(collection of vectors)
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
arr=np.zeros([2,3,4])  #3d tensor(collection of 2d tensors)
arr_random=np.random.rand(2,3,4)
arr_random

array([[[0.67481691, 0.54921007, 0.31864992, 0.20855123],
        [0.89903169, 0.26366049, 0.57057962, 0.38242596],
        [0.51702696, 0.02367753, 0.45448802, 0.72393527]],

       [[0.09025192, 0.94725068, 0.95032794, 0.44938348],
        [0.26397627, 0.41187764, 0.40989385, 0.70981043],
        [0.17147999, 0.35295903, 0.09561575, 0.64342428]]])

In [30]:
arr=np.zeros([2,3,4,5])   #4d tennsor(collection of 3d tensors)
arr_random=np.random.rand(2,3,4,5)
arr_random

array([[[[0.57780231, 0.11016861, 0.77285668, 0.80404982, 0.00366977],
         [0.37230946, 0.00818851, 0.94003859, 0.23068445, 0.46524833],
         [0.30790845, 0.98449675, 0.23082255, 0.48965437, 0.85287896],
         [0.14116357, 0.76076285, 0.76431925, 0.73612028, 0.34023771]],

        [[0.85858633, 0.35800953, 0.74768448, 0.18669983, 0.53561205],
         [0.33382238, 0.9936857 , 0.6294853 , 0.80050811, 0.62337929],
         [0.39676446, 0.00464883, 0.7053031 , 0.08886861, 0.23698367],
         [0.26540476, 0.03642834, 0.4721594 , 0.04472683, 0.35953294]],

        [[0.24045212, 0.92222457, 0.45014058, 0.09869776, 0.80615287],
         [0.41686742, 0.78232353, 0.7063202 , 0.53625486, 0.43613659],
         [0.07427922, 0.47116197, 0.81040272, 0.23527932, 0.87550715],
         [0.73116113, 0.55315237, 0.70781269, 0.64297588, 0.07946884]]],


       [[[0.9624188 , 0.5842724 , 0.77630766, 0.49923375, 0.68534649],
         [0.24477741, 0.14117549, 0.64576474, 0.50784199, 0.44169779]

In [32]:
arr=np.zeros([2,3,4,5,6])  #5d tensors(collection of 4d tensors)
arr_random=np.random.rand(2,3,4,5,6)
arr_random

array([[[[[7.93125562e-01, 8.77695856e-01, 4.35530079e-01,
           3.32885045e-02, 5.49988112e-01, 2.46836348e-01],
          [1.93033482e-01, 3.56422138e-01, 7.95368685e-01,
           8.08315099e-02, 1.53676974e-01, 7.52946997e-02],
          [5.08762653e-01, 8.59104702e-01, 9.78999928e-01,
           4.31382759e-01, 8.10658964e-01, 5.13913201e-01],
          [3.57977069e-01, 2.26723521e-02, 4.28267198e-01,
           2.06055805e-01, 8.94137315e-01, 6.74139090e-01],
          [4.07087825e-01, 4.67162865e-01, 6.09986021e-02,
           1.96936519e-01, 2.15777827e-01, 5.79514647e-01]],

         [[7.43820486e-01, 5.22007074e-01, 8.03038963e-01,
           9.82854598e-02, 2.62919725e-01, 1.00285765e-01],
          [9.60025960e-01, 1.79952053e-01, 6.24602141e-02,
           5.48762471e-01, 1.83879339e-01, 6.81805513e-01],
          [2.45663862e-01, 2.28705714e-01, 3.37230025e-01,
           9.92352449e-02, 4.69090454e-01, 5.37787114e-01],
          [3.30132430e-01, 8.81655606e-02, 3.5