In [4]:
import numpy as np
print(np.array([1,2,3,4]).reshape(2,2))
print(np.array([[1,2,3,4]]))
print(np.array([[[1,2,3,4]]]))
print(np.arange(1,10))
print(np.ones([2,3])) #both are used for array intializations
print(np.zeros([2,3]))
print(np.linspace(10,-10,10))
print(np.random.random(24))
print(np.identity(4))

[[1 2]
 [3 4]]
[[1 2 3 4]]
[[[1 2 3 4]]]
[1 2 3 4 5 6 7 8 9]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[ 10.           7.77777778   5.55555556   3.33333333   1.11111111
  -1.11111111  -3.33333333  -5.55555556  -7.77777778 -10.        ]
[0.18109763 0.9285986  0.43218521 0.49148221 0.82677734 0.4657294
 0.90326356 0.39790372 0.99056938 0.95587903 0.24268579 0.06130128
 0.02095055 0.64191061 0.62733752 0.98320959 0.85773989 0.12405496
 0.81181671 0.67837995 0.34459449 0.50286923 0.4055995  0.01819595]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
a1=np.array([1,2,3,4])
a2=np.array([[1,2,3,4]],dtype=float)
a3=np.arange(8).reshape(2,2,2)
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)
print(a1.shape)
print(a2.shape)
print(a3.shape)
print(a1.size)
print(a2.size)
print(a3.size)
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

1
2
3
(4,)
(1, 4)
(2, 2, 2)
4
4
8
4
8
4
int32
float64
int32


In [16]:
a2.astype(np.int32) #to change the datatype of an array

array([[1, 2, 3, 4]])

In [66]:
print(np.max(a3)) 
print(np.min(a3))
print(np.prod(a3,axis=0)) # 0 for column and 1 for row
print(np.mean(a3))
print(np.median(a3))
print(np.std(a3))
print(np.var(a3))
a3*2 #scalar operations
a1+a2 #vector operations
# a1.dot(a2) #dot product
a4=np.random.random((3,4))
np.ceil(a4)
np.floor(a4)
np.round(a4*100)
print(np.exp(a4*100))
print(a4[-1])
print(a4)
print(a4[1,1]) #first mention the row then the colummn

7
0
[[ 0  5]
 [12 21]]
3.5
3.5
2.29128784747792
5.25
[[1.81743621e+36 6.13782540e+30 1.34682665e+15 5.85633319e+37]
 [1.57428845e+39 3.15089328e+24 1.40756521e+17 1.15192775e+37]
 [8.55784409e+35 6.29585043e+30 1.87552009e+32 4.18163962e+07]]
[0.82737327 0.70917444 0.74311609 0.17548799]
[[0.8349049  0.70892023 0.34836528 0.86963172]
 [0.90254622 0.56409728 0.39485808 0.85337085]
 [0.82737327 0.70917444 0.74311609 0.17548799]]
0.564097282240968


In [70]:
a3[1,0,1] #first mention the 2d array number then do the normal slicing

5

In [20]:
a5=np.arange(12,24).reshape(6,2)
a6=np.arange(12).reshape(6,2)
np.hstack((a5,a6))
np.vstack((a5,a6))
np.hsplit(a5,2)
np.vsplit(a5,2)
a5.T
for i in np.nditer(a5):
    print(i)
print(a5.ravel())
print(np.eye(3,4)) #there are ones along the diagonals and zeros everywhere else
arr=np.arange(10,20).reshape(2,5)
print(np.tile(arr,(5,2)))
print(np.repeat(arr,2))
a6=np.array([5,6,7,8])
a7=np.array([1,2,9,2])
np.maximum(a6,a7)
np.sort(a7)[::-1]

12
13
14
15
16
17
18
19
20
21
22
23
[12 13 14 15 16 17 18 19 20 21 22 23]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[10 11 12 13 14 10 11 12 13 14]
 [15 16 17 18 19 15 16 17 18 19]
 [10 11 12 13 14 10 11 12 13 14]
 [15 16 17 18 19 15 16 17 18 19]
 [10 11 12 13 14 10 11 12 13 14]
 [15 16 17 18 19 15 16 17 18 19]
 [10 11 12 13 14 10 11 12 13 14]
 [15 16 17 18 19 15 16 17 18 19]
 [10 11 12 13 14 10 11 12 13 14]
 [15 16 17 18 19 15 16 17 18 19]]
[10 10 11 11 12 12 13 13 14 14 15 15 16 16 17 17 18 18 19 19]


array([9, 2, 2, 1])