In [60]:
import numpy as np
print(np.array([1,2,3,4]).reshape(2,2))
print(np.array([[1,2,3,4]]))
print(np.array([[[1,2,3,4]]]))
print(np.arange(1,10))
print(np.ones([2,3])) #both are used for array intializations
print(np.zeros([2,3]))
print(np.linspace(10,-10,10))
print(np.random.random(24))
print(np.identity(4))

[[1 2]
 [3 4]]
[[1 2 3 4]]
[[[1 2 3 4]]]
[1 2 3 4 5 6 7 8 9]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[ 10.           7.77777778   5.55555556   3.33333333   1.11111111
  -1.11111111  -3.33333333  -5.55555556  -7.77777778 -10.        ]
[0.26429169 0.16475916 0.75717088 0.82443219 0.42233443 0.1093465
 0.84764202 0.43503636 0.69830775 0.36464456 0.38789258 0.22450416
 0.48564369 0.88834715 0.02280694 0.39942198 0.79032381 0.93754481
 0.23774595 0.35846987 0.67524505 0.39433373 0.08263188 0.79755447]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [76]:
a1=np.array([1,2,3,4])
a2=np.array([[1,2,3,4]],)
a3=np.arange(8).reshape(2,2,2)
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)
print(a1.shape)
print(a2.shape)
print(a3.shape)
print(a1.size)
print(a2.size)
print(a3.size)
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

1
2
3
(4,)
(1, 4)
(2, 2, 2)
4
4
8
4
4
4
int32
int32
int32
